### PR TITLE
AphA CPD Survey data added

### PR DESCRIPTION
**Pull request by francisbarton**
- [x] Reproducible raw data import and cleaning script, with comments and context
- [x] Cleaning script in `data-raw` folder as suggested by `{usethis}`/_"R Packages"_
- [x] Clean column names and variable label attributes provided
- [x] Dataset documented (not to column level, but adequately?)

In response to issue #64.

### CODE REVIEW

**Comment by francisbarton** [comment]
Thanks @StatsRhian I'll have a look and see if I can find out why the checks are failing. It would be good to get this approved at long last. There was a thread about it on the NHS-R Slack but that is definitely lost to the mists of time now.

**Comment by StatsRhian** [comment]
Happy to help debug the logs too when you rerun. But I because it's your fork I can't retrigger them to have a look.
Yeah I'm guessing that's lost slack-history.

**Review by StatsRhian — APPROVED** [review]

**Comment by Lextuga007** [comment]
@all-contributors please add @francisbarton for code.

**Comment by Lextuga007** [comment]
@all-contributors please add @StatsRhian for maintenance.

**Comment by Lextuga007** [comment]
@all-contributors please add @francisbarton for data

**Pull request merged**
