### PR TITLE
ONS mortality

### PR DESCRIPTION
**Pull request by Lextuga007**
The original code is in a new folder called Working files. This can be ignored for the package.

### CODE REVIEW

**Comment by Lextuga007** [comment]
I'm happy for the 'Working files' directory to go into to the .Rbuildignore. I missed a commit to remove the .RData file as I'd moved it, so I've corrected that now. I'm going to put a .csv file version of the .RData file there for those who want it in .csv version. Being in .Rbuildignore that should be ignored by the package I hope but let me know if that's a problem.

I'll definitely write a vignette. I've used this data before for a dygraph chart that Ian Bowns originally built and I can codesome ggplot2 charts of data over time too. Thanks for the skeleton vignette, that's helpful as I've not written one before.

Thanks too for renaming the data file.

**Comment by chrismainey** [comment]
Great, thanks will merge now.  Are you happy to proceed with the static dataset, or do you want to go down the updater  function route that @tomjemmett was discussing on Slack.

**Comment by Lextuga007** [comment]
Yes, very happy with the updater function idea @tomjemmett suggested. Thanks.

**Comment by tomjemmett** [comment]
I think there are a few suggestions for functions to get data from api's or pull in datasets that are larger than the cran limits. We could pick this up via NHS-R slack if we want to implement this!

**Pull request merged**
